### ISSUE TITLE
让渡居官网Title、图标、重定向问题

### ISSUE THREAD

**Issue by LiteSun** [rangduju/rangduju.github.io#23]
1、网站  title 
2、网站图标 Favicon.ico
3、网站主页的路径重定向

![image](https://user-images.githubusercontent.com/31329157/64004566-0e9d1880-cb41-11e9-8e96-7ef4d027116b.png)

**Comment by qzcool** [comment]
@LiteSun 请准确以具体问题命名Issues，避免模糊。

**Comment by jidilang** [comment]
1、官网Title、图标已更换（解决）
2、重定向（为解决，遇到问题：需要在服务其中配置，但是目前没有服务器）https://react-guide.github.io/react-router-cn/docs/guides/basics/Histories.html
