### ISSUE TITLE
短租需求增长曲线切换效果健壮性检查

### ISSUE THREAD

**Issue by qzcool** [rangduju/rangduju.github.io#29]
![image](https://user-images.githubusercontent.com/10396208/64006908-cb917400-cb45-11e9-8fde-6cc37d97d282.png)
个人电脑切换效果失灵，请检查。

**Comment by jidilang** [comment]
电脑加载问题

**Comment by jidilang** [comment]
Mac电脑首次加载慢

**Comment by jidilang** [comment]
首次加载速度慢修改建议：1、在前端上优化速度    2、把图片上传到腾讯云存储

**Comment by jidilang** [comment]
前端上做了优化，等部署检查之后如果没问题才可关闭

**Comment by jidilang** [comment]
已解决
