### ISSUE TITLE
关于我们插入Airtable的团队介绍表格

### ISSUE THREAD

**Issue by qzcool** [rangduju/rangduju.github.io#32]
![image](https://user-images.githubusercontent.com/10396208/64090461-d59db780-cd7d-11e9-82bf-d4558a23999c.png)
请向我申请该Table的嵌入代码。

**Comment by qzcool** [comment]
`<iframe class="airtable-embed" src="https://airtable.com/embed/shrRfme06EYHbf6qB?backgroundColor=yellowLight&viewControls=on" frameborder="0" onmousewheel="" width="100%" height="533" style="background: transparent; border: 1px solid #ccc;"></iframe>`

**Comment by qzcool** [comment]
@jidilang 已经在企业微信私信给你嵌入代码。

**Comment by jidilang** [comment]
已添加
