### ISSUE TITLE
首页插入介绍视频

### ISSUE THREAD

**Issue by qzcool** [rangduju/rangduju.github.io#34]
![image](https://user-images.githubusercontent.com/10396208/64092951-3088dc00-cd89-11e9-9412-8ff4b06ff7d1.png)

**Comment by jidilang** [comment]
已完成

**Comment by qzcool** [comment]
@jidilang 马虎！请使用有声版视频，请再次检查TB。马虎！

**Comment by jidilang** [comment]
已更改

**Comment by qzcool** [comment]
请将该视频改为点击悬浮显示。

**Comment by jidilang** [comment]
已修改
