### ISSUE TITLE
域名的多余#号

### ISSUE THREAD

**Issue by qzcool** [rangduju/rangduju.github.io#38]
![image](https://user-images.githubusercontent.com/10396208/64405624-3b59ae80-d0b2-11e9-8b2f-133ea29d4cc3.png)

**Comment by LiteSun** [comment]
经排查发现是代码内部原因而非deploy 配置问题，测试后推到线上

![image](https://user-images.githubusercontent.com/31329157/64468459-a3ae9b80-d157-11e9-92e6-72d6cde19f7c.png)

![image](https://user-images.githubusercontent.com/31329157/64468467-d5bffd80-d157-11e9-9d76-4ac20d7bee08.png)

**Comment by qzcool** [comment]
👍

**Comment by LiteSun** [comment]
done，如果还会出现/#/，需要手动清除本地缓存

![image](https://user-images.githubusercontent.com/31329157/64469138-a9a87a80-d15f-11e9-9e4b-d7889d91ff20.png)

**Comment by qzcool** [comment]
好的，可以关了。
