### ISSUE TITLE
服务人次自动更新

### ISSUE THREAD

**Issue by anttan3** [rangduju/rangduju.github.io#43]
![image](https://user-images.githubusercontent.com/51979274/65480090-bf899f80-dec2-11e9-976a-d330de24b88d.png)
方法一：连通后台数据库，做到实时反馈服务人次和间夜次的增长变化
方法二：写一个脚本函数，放在后台运行，不定期更新数字，根据预估的房量推测累计的服务人数。（积分）

**Comment by qzcool** [comment]
支持该任务。

**Comment by jidilang** [comment]
以实现

**Comment by jidilang** [comment]
11、12需要隐藏吗？

**Comment by jidilang** [comment]
![image](https://user-images.githubusercontent.com/45256071/66814267-e6d70800-ef68-11e9-9511-7d0b4b9c4b02.png)

**Comment by anttan3** [comment]
未来2个月份不需要隐藏，只需要同最新数据持平即可。
