### ISSUE TITLE
`如何合作`加入设计服务

### ISSUE THREAD

**Issue by qzcool** [rangduju/rangduju.github.io#44]
租房五金少女赋能。

**Comment by jidilang** [comment]
已添加

**Comment by anttan3** [comment]
http://49.234.214.140/cooperation
第三条放置：
**房屋改造升级**
业主自主决定装修升级，时间成本灵活，方案可选。让渡居与人气设计品牌——租房五金少女达成战略合作关系，五金少女获得腾讯投资、拥有多平台共计超过百万粉丝，为让渡居旗下房屋组合提供因房制宜的设计改造方案。

**Comment by jidilang** [comment]
已添加
