### ISSUE TITLE
首页设计：Columns调整

### ISSUE THREAD

**Issue by anttan3** [rangduju/rangduju.github.io#7]
# column调整建议

以下属于排版的调整要求，括号中是对细节的修改，可以再行商量。

## Frontier

左侧放logo

## column

column1：宽屏大图

column2：让渡居 名字

column3：短租潜力预测+房源委托管理

column4：我们因何存在？（文字全部展示）

column5：品牌故事（只露出三至五行+其余read more）

column6：用户评价
1. user加头像；2 user名下加地区和评论时间。参考lyric的做法：
The space is truly amazing! The views are breathtaking. All of the finishes, including bath products, were top-notch.
Jovas
Philadelphia
January 2019

## Footer

加上座机电话010-85890977

**Comment by anttan3** [comment]
宽屏大图研究一下是否可以加上滚动播放的功能。图片素材如下：
![rhema-kallianpur-uocSnWMhnAs-unsplash](https://user-images.githubusercontent.com/51979274/60755626-e1425b80-a024-11e9-90a0-81624cb0e472.jpg)
![curology-29wToZsX0Is-unsplash](https://user-images.githubusercontent.com/51979274/60755627-e1daf200-a024-11e9-8d8a-ee6e1ba2eee7.jpg)
![davide-cantelli-ajisKc2uuFk-unsplash](https://user-images.githubusercontent.com/51979274/60755629-e30c1f00-a024-11e9-86f4-cb543e536e57.jpg)
![plqml-feliperizo-co-BmoOdR6YP9o-unsplash](https://user-images.githubusercontent.com/51979274/60755630-e3a4b580-a024-11e9-9a22-faf9c23494c7.jpg)

**Comment by qzcool** [comment]
@anttan3 可以学习如何使用[墨刀](https://modao.cc)来做产品原型图。
